(function(){'use strict';const revEls=document.querySelectorAll('.reveal,.reveal-l,.reveal-r');if('IntersectionObserver'in window){const revObs=new IntersectionObserver(function(entries){entries.forEach(function(e){if(e.isIntersecting){e.target.classList.add('in');revObs.unobserve(e.target);}});},{threshold:0.08});revEls.forEach(function(el){revObs.observe(el);});}else{revEls.forEach(function(el){el.classList.add('in');});}
var sticky=document.getElementById('sticky');var backTop=document.getElementById('back-top');var ticking=false;function onScroll(){if(!ticking){requestAnimationFrame(function(){var y=window.scrollY;if(sticky)sticky.classList.toggle('show',y>500);if(backTop)backTop.classList.toggle('show',y>800);ticking=false;});ticking=true;}}
window.addEventListener('scroll',onScroll,{passive:true});var _cdKey='ac_cd';var _cdSaved=sessionStorage.getItem(_cdKey);var ch,cm,cs;if(_cdSaved){var p=_cdSaved.split(',');ch=+p[0];cm=+p[1];cs=+p[2];if(ch===0&&cm===0&&cs===0){ch=4;cm=23;cs=59;}}else{ch=4;cm=23;cs=59;}
var dH=document.getElementById('cdH');var dM=document.getElementById('cdM');var dS=document.getElementById('cdS');if(dH&&dM&&dS){setInterval(function(){if(--cs<0){cs=59;if(--cm<0){cm=59;if(--ch<0){ch=cm=cs=0;}}}
dH.textContent=String(ch).padStart(2,'0');dM.textContent=String(cm).padStart(2,'0');dS.textContent=String(cs).padStart(2,'0');sessionStorage.setItem(_cdKey,[ch,cm,cs].join(','));},1000);}
var acSlider=document.getElementById('ac-slider');var hrSlider=document.getElementById('hr-slider');var acVal=document.getElementById('ac-val');var hrVal=document.getElementById('hr-val');var wResult=document.getElementById('waste-result');var cvBad=document.getElementById('cv-bad');var cvSave=document.getElementById('cv-save');function calcWaste(){if(!acSlider||!hrSlider)return;var ac=parseInt(acSlider.value);var hr=parseInt(hrSlider.value);var wastePerMo=120*(hr/8)*ac;var wastePerYr=Math.round(wastePerMo*12/100)*100;var acPct=((ac-1)/5*100).toFixed(1)+'%';var hrPct=((hr-4)/14*100).toFixed(1)+'%';var fmt=function(n){return'฿'+n.toLocaleString();};requestAnimationFrame(function(){if(wResult)wResult.textContent=fmt(wastePerYr);if(cvBad)cvBad.textContent=fmt(wastePerYr);if(cvSave)cvSave.textContent=fmt(wastePerYr);if(acVal)acVal.textContent=ac+' เครื่อง';if(hrVal)hrVal.textContent=hr+' ชั่วโมง';acSlider.style.setProperty('--pct',acPct);hrSlider.style.setProperty('--pct',hrPct);});}
if(acSlider)acSlider.addEventListener('input',calcWaste);if(hrSlider)hrSlider.addEventListener('input',calcWaste);calcWaste();window.toggleF=function(btn){var ans=btn.nextElementSibling;var isOpen=ans.classList.contains('open');document.querySelectorAll('.fans').forEach(function(a){a.classList.remove('open');});document.querySelectorAll('.fbtn').forEach(function(b){b.classList.remove('open');});if(!isOpen){ans.classList.add('open');btn.classList.add('open');}};window.submitForm=function(btn){var fieldMap=[{id:'f-name',label:'กรุณากรอกชื่อของคุณ'},{id:'f-tel',label:'กรุณากรอกเบอร์โทรศัพท์'},{id:'f-qty',label:'กรุณาเลือกจำนวนแอร์'},];var ok=true;var firstErr=null;fieldMap.forEach(function(f){var el=document.getElementById(f.id);if(!el)return;if(!el.value.trim()){el.classList.add('error');el.classList.remove('ok');el.setAttribute('placeholder',f.label);ok=false;if(!firstErr)firstErr=el;}else{el.classList.remove('error');el.classList.add('ok');}});var errDiv=document.getElementById('form-err');if(!ok){if(errDiv){errDiv.textContent='กรุณากรอกข้อมูลที่จำเป็นให้ครบก่อนนะคะ';errDiv.classList.add('show');}
if(firstErr)firstErr.focus();return;}
if(errDiv)errDiv.classList.remove('show');btn.textContent='✅ รับจองเรียบร้อย! ทีมงานจะโทรยืนยันภายใน 5 นาที';btn.style.background='linear-gradient(135deg,#1a6b3a,#2e7d32)';btn.style.color='#fff';btn.disabled=true;if(typeof gtag==='function'){gtag('event','conversion',{event_category:'lead',event_label:'booking_form'});}
if(typeof fbq==='function'){fbq('track','Lead');}};(function(){var KEY='ac_slots';var MIN=1;var slots=parseInt(localStorage.getItem(KEY));if(isNaN(slots)||slots>7||slots<MIN)slots=7;function renderSlots(n){var row=document.querySelector('.slots-row');if(row){var taken=15-n;var html='';for(var i=0;i<taken;i++)html+='<div class="slot taken" title="จองแล้ว"></div>';for(var j=0;j<n;j++)html+='<div class="slot open" title="ว่าง — จองได้เลย">📅</div>';row.innerHTML=html;}
var cap=document.querySelector('.slots-caption');if(cap)cap.innerHTML='จองแล้ว '+(15-n)+' คิว &nbsp;&middot;&nbsp; ว่างอยู่ <strong style="color:var(--gold)">'+n+' คิวสุดท้าย</strong>';var sMsg=document.querySelector('.sticky-msg');if(sMsg)sMsg.innerHTML='&#128293; เหลือ <strong>'+n+' คิวสุดท้าย</strong> &mdash; โปรสัปดาห์นี้';var urgSpan=document.querySelector('#urgency h2 span');if(urgSpan)urgSpan.textContent=n+' คิวสุดท้าย';}
renderSlots(slots);function scheduleDecrease(){var delay=(8+Math.random()*10)*60*1000;setTimeout(function(){if(slots>MIN){slots--;localStorage.setItem(KEY,slots);renderSlots(slots);}
scheduleDecrease();},delay);}
scheduleDecrease();})();var popup=document.getElementById('sp-popup');var spMsg=document.getElementById('sp-msg');var spTime=document.getElementById('sp-time');var _allNotifs=[{name:'สมหญิง',loc:'ลาดพร้าว',action:'กำลังดูหน้านี้อยู่ด้วยตอนนี้'},{name:'ธนพล',loc:'บางนา',action:'เพิ่งจองคิวล้างแอร์ไปเมื่อกี้'},{name:'พรทิพย์',loc:'จตุจักร',action:'กำลังดูหน้านี้อยู่ด้วยตอนนี้'},{name:'อนุชา',loc:'พระโขนง',action:'เพิ่งจองคิวล้างแอร์ไปเมื่อกี้'},{name:'วารุณี',loc:'ลาดกระบัง',action:'กำลังดูแพ็คเกจ Standard อยู่'},{name:'สุรศักดิ์',loc:'มีนบุรี',action:'เพิ่งจองคิวล้างแอร์ไปเมื่อกี้'},{name:'กานดา',loc:'บางแค',action:'กำลังดูหน้านี้อยู่ด้วยตอนนี้'},{name:'ธีรวัฒน์',loc:'ดินแดง',action:'เพิ่งกดจองแพ็คเกจ Premium ไป'},{name:'นภาพร',loc:'สาทร',action:'กำลังดูแพ็คเกจ Premium อยู่'},{name:'ประภาส',loc:'รามคำแหง',action:'เพิ่งจองคิวล้างแอร์ไปเมื่อกี้'},{name:'มณีรัตน์',loc:'ห้วยขวาง',action:'กำลังดูหน้านี้อยู่ด้วยตอนนี้'},{name:'รัชนี',loc:'ลาดกระบัง',action:'เพิ่งจองแพ็คเกจ Standard ไป'},{name:'วีระ',loc:'บางรัก',action:'กำลังดูแพ็คเกจ Basic อยู่'},{name:'ศิริพร',loc:'สะพานสูง',action:'เพิ่งจองคิวล้างแอร์ไปเมื่อกี้'},{name:'สมชาย',loc:'คลองสาน',action:'กำลังดูหน้านี้อยู่ด้วยตอนนี้'},{name:'หทัยทิพย์',loc:'ประเวศ',action:'เพิ่งกดจองแพ็คเกจ Standard ไป'},{name:'อภิชาติ',loc:'ลาดพร้าว',action:'กำลังดูแพ็คเกจ Premium อยู่'},{name:'กิตติพงษ์',loc:'บึงกุ่ม',action:'เพิ่งจองคิวล้างแอร์ไปเมื่อกี้'},{name:'ชนิดา',loc:'ธนบุรี',action:'กำลังดูหน้านี้อยู่ด้วยตอนนี้'},{name:'ณัฐวุฒิ',loc:'ราษฎร์บูรณะ',action:'เพิ่งจองแพ็คเกจ Basic ไป'},{name:'ทิพย์วรรณ',loc:'ดอนเมือง',action:'กำลังดูแพ็คเกจ Standard อยู่'},{name:'บุญมี',loc:'หลักสี่',action:'เพิ่งจองคิวล้างแอร์ไปเมื่อกี้'},{name:'ปาริชาต',loc:'บางเขน',action:'กำลังดูหน้านี้อยู่ด้วยตอนนี้'},{name:'ไพโรจน์',loc:'ตลิ่งชัน',action:'เพิ่งกดจองแพ็คเกจ Premium ไป'},{name:'ยุพา',loc:'บางพลัด',action:'กำลังดูแพ็คเกจ Basic อยู่'},];function shuffle(arr){var a=arr.slice();for(var i=a.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1));var t=a[i];a[i]=a[j];a[j]=t;}
return a;}
var _times=['เมื่อกี้','1 นาทีที่แล้ว','2 นาทีที่แล้ว','3 นาทีที่แล้ว','5 นาทีที่แล้ว','7 นาทีที่แล้ว','10 นาทีที่แล้ว'];var _queue=shuffle(_allNotifs);var _qIdx=0;function showNotification(){if(!popup||!spMsg||!spTime)return;if(_qIdx>=_queue.length){_queue=shuffle(_allNotifs);_qIdx=0;}
var n=_queue[_qIdx++];var t=_times[Math.floor(Math.random()*_times.length)];spMsg.innerHTML='<strong>'+n.name+' จาก '+n.loc+'</strong><br>'+n.action;spTime.textContent=t;popup.classList.add('show');setTimeout(function(){popup.classList.remove('show');},4500);}
function scheduleNotif(){var isMobile=window.innerWidth<768;var minDelay=isMobile?35:20;var range=isMobile?20:15;var delay=(minDelay+Math.random()*range)*1000;setTimeout(function(){showNotification();scheduleNotif();},delay);}
var firstDelay=window.innerWidth<768?12000:6000;setTimeout(function(){showNotification();scheduleNotif();},firstDelay);})();(function(){var banner=document.getElementById('consent-banner');if(!banner)return;var CONSENT_KEY='ac_consent';if(localStorage.getItem(CONSENT_KEY)){banner.classList.add('hidden');return;}
function dismiss(){banner.classList.add('hidden');document.body.style.paddingBottom='56px';}
var btnAccept=document.getElementById('consent-accept');var btnReject=document.getElementById('consent-reject');if(btnAccept)btnAccept.addEventListener('click',function(){localStorage.setItem(CONSENT_KEY,'accepted');dismiss();});if(btnReject)btnReject.addEventListener('click',function(){localStorage.setItem(CONSENT_KEY,'essential');dismiss();});})();